### ISSUE TITLE
本地部署运行scrapy crawl zhihu 报错

### ISSUE THREAD

**Issue by WayneLeiCode** [mtianyan/FunpySpiderSearchEngine#29]
2021-03-24 18:26:53 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET http://www.zhihu.com/app/> from <GET https://www.zhihu.com/app?auto_download=true&utm_source=zhihu&utm_campaign=guest_feed&utm_content=guide>
2021-03-24 18:26:53 [scrapy.core.engine] DEBUG: Crawled (400) <GET https://www.zhihu.com?utm_source=zhihu&utm_campaign=guest_feed&utm_content=guide> (referer: https://www.zhizhu.com)
2021-03-24 18:26:53 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <400 https://www.zhihu.com?utm_source=zhihu&utm_campaign=guest_feed&utm_content=guide>: HTTP status code is not handled or not allowed
2021-03-24 18:26:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.zhihu.com/signin?next=http%3A%2F%2Fwww.zhihu.com%2Fquestion%2F28227721> (referer: https://www.zhizhu.com)
2021-03-24 18:26:54 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.zhihu.com/signin?next=http%3A%2F%2Fwww.zhihu.com%2Fquestion%2F28227721> (referer: https://www.zhizhu.com)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/home/search/FunpySpiderSearchEngine/mtianyanSpider/spiders/zhihu.py", line 113, in parse_question
    item_loader.add_value("zhihu_id", question_id)
  File "/usr/local/python3/lib/python3.7/site-packages/itemloaders/__init__.py", line 190, in add_value
    self._add_value(field_name, value)
  File "/usr/local/python3/lib/python3.7/site-packages/itemloaders/__init__.py", line 208, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "/usr/local/python3/lib/python3.7/site-packages/itemloaders/__init__.py", line 312, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "/usr/local/python3/lib/python3.7/site-packages/itemloaders/__init__.py", line 293, in get_input_processor
    self.default_input_processor
  File "/usr/local/python3/lib/python3.7/site-packages/itemloaders/__init__.py", line 308, in _get_item_field_attr
    field_meta = ItemAdapter(self.item).get_field_meta(field_name)
  File "/usr/local/python3/lib/python3.7/site-packages/itemadapter/adapter.py", line 89, in get_field_meta
    return MappingProxyType(self.item.fields[field_name])
KeyError: 'zhihu_id'

**Comment by mtianyan** [comment]
@Holyfiled 需要在mtianyanSpider/cookies/zhihu.cookie 替换自己登陆后的cookie哈
